"""Change DATABASE

Revision ID: 06b585727599
Revises: 219c8697da7d
Create Date: 2025-07-03 19:48:59.070410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06b585727599'
down_revision = '219c8697da7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('nmap_result', sa.Text(), nullable=True),
    sa.Column('whois_result', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('whois_records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whois_records',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('domain', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('registrar', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('creation_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('expiration_date', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('whois_records_pkey')),
    sa.UniqueConstraint('domain', name=op.f('whois_records_domain_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('local_scans')
    # ### end Alembic commands ###
