"""File Analisis new Implement in database

Revision ID: 219c8697da7d
Revises: 9252a20b13ec
Create Date: 2025-07-03 17:57:19.809451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '219c8697da7d'
down_revision = '9252a20b13ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_analysis', schema=None) as batch_op:
        batch_op.alter_column('line_count',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('malicious',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_analysis', schema=None) as batch_op:
        batch_op.alter_column('malicious',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('line_count',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
