"""NUEVA MIGRACION HIPN ADDITION

Revision ID: abb56f95cdba
Revises: 62eed9febe4c
Create Date: 2025-07-07 00:21:12.640971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abb56f95cdba'
down_revision = '62eed9febe4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_breach_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha1_hash', sa.String(length=40), nullable=False),
    sa.Column('leaked', sa.Boolean(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.Column('query_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('password_breach_queries')
    # ### end Alembic commands ###
