"""Primera migración

Revision ID: c1292b03fe52
Revises: 
Create Date: 2025-07-03 12:08:13.401174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1292b03fe52'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('file_analysis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('malicious', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_analysis', schema=None) as batch_op:
        batch_op.drop_column('malicious')
        batch_op.drop_column('content')

    # ### end Alembic commands ###
