"""Initial migration 4

Revision ID: c8072d71a78b
Revises: 7e08e75de01a
Create Date: 2025-07-05 00:05:18.205655

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c8072d71a78b'
down_revision = '7e08e75de01a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supershodan_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=False),
    sa.Column('scan_date', sa.DateTime(), nullable=True),
    sa.Column('theharvester_results', sa.JSON(), nullable=True),
    sa.Column('nmap_results', sa.Text(), nullable=True),
    sa.Column('whois_results', sa.Text(), nullable=True),
    sa.Column('dns_results', sa.JSON(), nullable=True),
    sa.Column('is_complete', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('shodan_lookups')
    with op.batch_alter_table('local_scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_local_scans_ip_address'))

    op.drop_table('local_scans')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_scans',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('nmap_result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('whois_result', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('local_scans_pkey'))
    )
    with op.batch_alter_table('local_scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_local_scans_ip_address'), ['ip_address'], unique=False)

    op.create_table('shodan_lookups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('open_ports', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('vulnerabilities', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('shodan_lookups_pkey'))
    )
    op.drop_table('supershodan_scans')
    # ### end Alembic commands ###
